spring:
  application:  
        name: object-store
  datasource:
      url: jdbc:h2:mem:api
      password: 
      username: sa
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true